[package]
name = "eventually-test"
version = "0.1.0"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventually = { path = "../eventually", features = ["full"] }
eventually-postgres = { path = "../eventually-postgres" }

chrono = { version = "0.4", features = ["serde"] }
envconfig = "0.8"
envconfig_derive = "0.8"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tide = "0.8"
tokio = { version = "0.2", features = ["macros", "sync"] }
tokio-postgres = "0.5"
