[package]
name = "eventually"
description = "Crate for using Event Sourcing in Rust applications"
version = "0.5.0"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/eventually-rs/eventually-rs"

categories = ["rust-patterns", "web-programming", "asynchronous", "data-structures"]
keywords = ["architecture", "ddd", "event-sourcing", "cqrs", "es"]

[features]

[dependencies]
anyhow = "1.0.38"
async-stream = "0.3.0"
async-trait = "0.1.48"
futures = "0.3.12"
serde = { version = "1.0.124", features = ["derive"] }
thiserror = "1.0.23"
tokio = { version = "1.2.0", features = ["sync"] }
tokio-stream = { version = "0.1.3", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.2.0", features = ["rt", "macros"] }
