[package]
name = "eventually"
description = "Crate for using Event Sourcing in Rust applications"
version = "0.4.0"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/ar3s3ru/eventually-rs"

categories = ["rust-patterns", "web-programming", "asynchronous", "data-structures"]
keywords = ["architecture", "ddd", "event-sourcing", "cqrs", "es"]

[features]
default = []
serde = ["eventually-core/serde", "eventually-util/serde"]
tokio = ["eventually-util/tokio"]
full = ["serde", "tokio"]

[dependencies]
eventually-core = { version = "0.4", path = "../eventually-core" }
eventually-util = { version = "0.4", path = "../eventually-util" }

[dev-dependencies]
futures = { version = "0.3", features = ["async-await"] }
tokio-test = "0.2"
