[package]
name = "eventually-postgres"
description = "Event Store implementation using PostgreSQL for the Eventually crate"
version = "0.2.0-alpha.1"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/ar3s3ru/eventually-rs"

categories = ["web-programming", "asynchronous"]
keywords = ["postgres", "postgresql", "database", "ddd", "event-sourcing"]

[dependencies]
eventually-core = { version = "0.4.0-alpha.1", path = "../eventually-core", features = ["full"] }

futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-postgres = { version = "0.5", features = ["with-serde_json-1"] }
thiserror = "1.0"
refinery = { version = "0.3.0", features = ["tokio-postgres"] }
anyhow = "1.0.32"
tokio = { version = "0.2", features = ["sync"] }
tracing = "0.1"

[dev-dependencies]
testcontainers = "0.9"
tokio = { version = "0.2", features = ["sync", "macros"] }
