[package]
name = "eventually-postgres"
version = "0.1.0"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"

[dependencies]
eventually-core = { path = "../eventually-core" }
eventually-util = { path = "../eventually-util", features = ["serde"] }

futures = "0.3"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["sync"] }
tokio-postgres = { version = "0.5", features = ["with-serde_json-1"] }
