[package]
name = "eventually-postgres"
description = "Event Store implementation using PostgreSQL for the Eventually crate"
version = "0.1.3"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/ar3s3ru/eventually-rs"

categories = ["web-programming", "asynchronous"]
keywords = ["postgres", "postgresql", "database", "ddd", "event-sourcing"]

[dependencies]
eventually = { version = "0.4", path = "../eventually", features = ["serde"] }

futures = "0.3"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["sync"] }
tokio-postgres = { version = "0.5", features = ["with-serde_json-1"] }
