[package]
name = "eventually-util"
description = "Extension crate containing utility components for using Event Sourcing in Rust applications"
version = "0.4.0"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/ar3s3ru/eventually-rs"

[features]
default = []
full = ["serde", "tokio"]

[dependencies]
eventually-core = { version = "0.4", path = "../eventually-core" }

futures = { version = "0.3", features = ["async-await"] }
serde = { version = "1.0", features = ["derive"], optional = true }
tokio = { version = "0.2", features = ["sync"], optional = true }

[dev-dependencies]
tokio-test = "0.2"
