[package]
name = "eventually-util"
version = "0.3.0"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"

[features]
default = []
full = ["serde", "tokio"]

[dependencies]
eventually-core = { path = "../eventually-core" }
futures = { version = "0.3", features = ["async-await"] }
serde = { version = "1.0", features = ["derive"], optional = true }
tokio = { version = "0.2", features = ["sync"], optional = true }
